return Def.ActorFrame{
	OnCommand=cmd(diffusealpha,.5);
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#F800F8");blend,'BlendMode_Add';zoomto,72,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0);
		OnCommand=cmd(x,SCREEN_CENTER_X-117;y,SCREEN_CENTER_Y+125);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#F800F8");blend,'BlendMode_Add';zoomto,22,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0;skewy,-.12);
		OnCommand=cmd(x,SCREEN_CENTER_X-164;y,SCREEN_CENTER_Y+134);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#F800F8");blend,'BlendMode_Add';zoomto,10,64;customtexturerect,0,0,.5,1;texcoordvelocity,.5,0;skewy,-.12);
		OnCommand=cmd(x,SCREEN_CENTER_X-88;y,SCREEN_CENTER_Y+134);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#F800F8");blend,'BlendMode_Add';zoomto,82,64;customtexturerect,0,0,.5,1;texcoordvelocity,.5,0);
		OnCommand=cmd(x,SCREEN_CENTER_X-134;y,SCREEN_CENTER_Y+140);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#00BBF8");blend,'BlendMode_Add';zoomto,88,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0);
		OnCommand=cmd(x,SCREEN_CENTER_X-234;y,SCREEN_CENTER_Y+145);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#00BBF8");blend,'BlendMode_Add';zoomto,58,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0;skewy,-.2);
		OnCommand=cmd(x,SCREEN_CENTER_X-307;y,SCREEN_CENTER_Y+159);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#00BBF8");blend,'BlendMode_Add';zoomto,43,64;customtexturerect,0,0,.5,1;texcoordvelocity,.5,0;skewy,-.2);
		OnCommand=cmd(x,SCREEN_CENTER_X-212;y,SCREEN_CENTER_Y+161);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#00BBF8");blend,'BlendMode_Add';zoomto,103,64;customtexturerect,0,0,.5,1;texcoordvelocity,.5,0);
		OnCommand=cmd(x,SCREEN_CENTER_X-285;y,SCREEN_CENTER_Y+174);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#00BBF8");blend,'BlendMode_Add';zoomto,85,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0);
		OnCommand=cmd(x,SCREEN_CENTER_X-47;y,SCREEN_CENTER_Y+145);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#00BBF8");blend,'BlendMode_Add';zoomto,2,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0;skewy,-.5);
		OnCommand=cmd(x,SCREEN_CENTER_X-6;y,SCREEN_CENTER_Y+158);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#00BBF8");blend,'BlendMode_Add';zoomto,20,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0;skewy,-.24);
		OnCommand=cmd(x,SCREEN_CENTER_X-100;y,SCREEN_CENTER_Y+161);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#00BBF8");blend,'BlendMode_Add';zoomto,102,64;customtexturerect,0,0,.5,1;texcoordvelocity,.5,0);
		OnCommand=cmd(x,SCREEN_CENTER_X-58;y,SCREEN_CENTER_Y+174);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#F800F8");blend,'BlendMode_Add';zoomto,112,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0);
		OnCommand=cmd(x,SCREEN_CENTER_X-176;y,SCREEN_CENTER_Y+178);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#F800F8");blend,'BlendMode_Add';zoomto,38,64;customtexturerect,0,0,.5,1;texcoordvelocity,.5,0;skewy,-.4);
		OnCommand=cmd(x,SCREEN_CENTER_X-139;y,SCREEN_CENTER_Y+203);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#F800F8");blend,'BlendMode_Add';zoomto,74,64;customtexturerect,0,0,.5,1;texcoordvelocity,-.5,0;skewy,-.4);
		OnCommand=cmd(x,SCREEN_CENTER_X-269;y,SCREEN_CENTER_Y+203);
	};
	LoadActor("light")..{
		InitCommand=cmd(diffuse,color("#F800F8");blend,'BlendMode_Add';zoomto,152,64;customtexturerect,0,0,.5,1;texcoordvelocity,.5,0);
		OnCommand=cmd(x,SCREEN_CENTER_X-232;y,SCREEN_CENTER_Y+227);
	};
}