return Def.ActorFrame {
	Def.Quad{
		OnCommand=cmd(x,119;y,SCREEN_CENTER_Y-192;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,left);
	};
	LoadActor("starp")..{
		OnCommand=cmd(x,69;y,SCREEN_CENTER_Y-192);
	};
	Def.Quad{
		OnCommand=cmd(x,39;y,SCREEN_CENTER_Y-128;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,left);
	};
	LoadActor("starp")..{
		OnCommand=cmd(x,-11;y,SCREEN_CENTER_Y-128);
	};
	Def.Quad{
		OnCommand=cmd(x,-41;y,SCREEN_CENTER_Y-64;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,left);
	};
	LoadActor("starp")..{
		OnCommand=cmd(x,-91;y,SCREEN_CENTER_Y-64);
	};
	Def.Quad{
		OnCommand=cmd(x,-121;y,SCREEN_CENTER_Y;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,left);
	};
	LoadActor("starp")..{
		OnCommand=cmd(x,-171;y,SCREEN_CENTER_Y);
	};
	Def.Quad{
		OnCommand=cmd(x,-201;y,SCREEN_CENTER_Y+64;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,left);
	};
	LoadActor("starp")..{
		OnCommand=cmd(x,-251;y,SCREEN_CENTER_Y+64);
	};
	Def.Quad{
		OnCommand=cmd(x,-281;y,SCREEN_CENTER_Y+128;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,left);
	};
	LoadActor("starp")..{
		OnCommand=cmd(x,-331;y,SCREEN_CENTER_Y+128);
	};
	Def.Quad{
		OnCommand=cmd(x,-361;y,SCREEN_CENTER_Y+192;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,left);
	};
	LoadActor("starp")..{
		OnCommand=cmd(x,-411;y,SCREEN_CENTER_Y+192);
	};
};