return Def.ActorFrame {
	Def.Quad{
		OnCommand=cmd(x,190;y,SCREEN_CENTER_Y-224;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,right);
	};
	LoadActor("stary")..{
		OnCommand=cmd(x,240;y,SCREEN_CENTER_Y-224;zoomx,-1);
	};
	Def.Quad{
		OnCommand=cmd(x,110;y,SCREEN_CENTER_Y-160;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,right);
	};
	LoadActor("stary")..{
		OnCommand=cmd(x,160;y,SCREEN_CENTER_Y-160;zoomx,-1);
	};
	Def.Quad{
		OnCommand=cmd(x,30;y,SCREEN_CENTER_Y-96;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,right);
	};
	LoadActor("stary")..{
		OnCommand=cmd(x,80;y,SCREEN_CENTER_Y-96;zoomx,-1);
	};
	Def.Quad{
		OnCommand=cmd(x,-50;y,SCREEN_CENTER_Y-32;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,right);
	};
	LoadActor("stary")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-32;zoomx,-1);
	};
	Def.Quad{
		OnCommand=cmd(x,-130;y,SCREEN_CENTER_Y+32;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,right);
	};
	LoadActor("stary")..{
		OnCommand=cmd(x,-80;y,SCREEN_CENTER_Y+32;zoomx,-1);
	};
	Def.Quad{
		OnCommand=cmd(x,-210;y,SCREEN_CENTER_Y+96;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,right);
	};
	LoadActor("stary")..{
		OnCommand=cmd(x,-160;y,SCREEN_CENTER_Y+96;zoomx,-1);
	};
	Def.Quad{
		OnCommand=cmd(x,-290;y,SCREEN_CENTER_Y+160;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,right);
	};
	LoadActor("stary")..{
		OnCommand=cmd(x,-240;y,SCREEN_CENTER_Y+160;zoomx,-1);
	};
	Def.Quad{
		OnCommand=cmd(x,-370;y,SCREEN_CENTER_Y+224;diffusecolor,Color.Black;zoomto,SCREEN_WIDTH*2,32;horizalign,right);
	};
	LoadActor("stary")..{
		OnCommand=cmd(x,-320;y,SCREEN_CENTER_Y+224;zoomx,-1);
	};
};